[project]
name = "polyhedral_net_splines"
version = "0.1.0"
requires-python = ">=3.7"
readme = "python/README.md"

[build-system]
requires = [
  "scikit-build-core>=0.7.0",
  "pybind11>=2.6.0"
]
build-backend = "scikit_build_core.build"
